<?php
$URL_PAGINA_INGRESO = "./";
$MODO_ALTA = "A";
$MODO_CAMBIO = "C";
$MAX_NUM_RESULTADOS_X_PAGINA = 5;
$ID_ITEM_NO_SELECCIONADO_EN_LISTA_SELECCION = 0;
$MAX_TIEMPO_TRANSCURRIDO_SEGUNDOS_DESDE_ULTIMO_USO_SESION = 5*60; // Se fija el máximo tiempo transcurrido en 5 minutos
$MOSTRAR_CONSULTAS_SQL = 0;
?>
